apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: mqtt
data:
  mosquitto.conf: |
    # Port for plaintext communication
    listener 1883

    # Location of the credentials file
    password_file /myuser/passwd

    # Port and certificates for TLS encrypted communication
    listener 8883
    certfile /myuser/server.crt
    cafile /myuser/ca.crt
    keyfile /myuser/server.key
