---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-ssl
  namespace: mqtt
spec:
  selector:
    app: mqtt
  ports:
    - protocol: TCP
      name: listener
      port: 8883

---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-service
  namespace: mqtt
spec:
  selector:
    app: mqtt
  ports:
    - protocol: TCP
      name: listener
      port: 1883
#   readinessProbe:
#     tcpSocket:
#       port: 1880
#     initialDelaySeconds: 5
#     periodSeconds: 10
