---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pvc-mqtt
      namespace: mqtt
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
      storageClassName: thin
